defmodule SurfaceAppWeb.Components.UserCard do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  @doc "The header slot"
  slot header

  @doc "The footer slot"
  slot footer

  @doc "The main content slot"
  slot default

  @doc "The background color"
  prop rounded, :boolean, default: false
  prop followed, :boolean, default: false
  prop itsme, :boolean, default: false

  prop user_follows, :list

  prop user, :any

  @doc """
  The max width.

  sm: `max-w-sm`, md: `max-w-md`, lg: `max-w-lg`
  """
  prop max_width, :string, values: ["sm", "md", "lg"]

  def render(assigns) do
    ~F"""
    <style>
      .card {
        @apply overflow-hidden shadow-lg;
      }
      .content {
        @apply border-1 border-black-500 px-6 py-4 text-gray-700 text-base;
      }
      .header {
        @apply p-6 font-semibold text-2xl text-teal-600 w-full bg-gray-200;
      }
      .footer {
        @apply px-6 py-4;
      }
    </style>
    <div class="flex p-4 w-full hover:scale-105 duration-500">
      <div class=" flex items-center justify-between p-2 rounded-lg bg-white shadow-indigo-50 shadow-md">
        <div>
        <div class={"card", "max-w-#{@max_width}", "rounded-2xl": @rounded}>
          <div class="header">
            <#slot {@header}/>
          </div>
          <div class="content">
            <div class="flex items-center justify-center">
                <!-- Filled in plus sign if followed -->
                {#if @itsme}
                ✴
                {#elseif @followed}
                  <button :on-click="toggle_follow" id="follow_btn">✅</button>
                {#else}
                  <button :on-click="toggle_follow" id="follow_btn">⛶</button>
                {/if}
              <#slot/>
            </div>
          </div>
          <div class="footer">
            <#slot {@footer}/>
          </div>
        </div>
        </div>
      </div>
    </div>
    """
  end
end
